title: Aster Fialla
description: Aster Fialla's portfolio, blog, and miscellaneous other things.
author: Aster Fialla
domain: asterfialla.com     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://asterfialla.com  # the base hostname and protocol for your site, e.g. http://example.com
layout: default
excerpt_separator: <!--more-->
collections_dir: collections
collections:
  twine:
    output: true
    permalink: games/:title
  piece:
    output: true
    permalink: games/:title
  ttrpg:
    output: true
    permalink: games/:title
  posts:
    output: true
    permalink: blog/:title

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll/tagging

feed:
  icon: /images/avvie.png
  excerpt_only: true
#  disable_in_development: true
  categories:
    - essays
    - devlogs
    - meta
    - poems
    - drawings
    - microblogs
  collections:
    - twine
    - ttrpg
    - piece

tag_page_layout: tagpage
tag_page_dir: blog/tag
tag_page_data:
  sitemap: false


defaults:
  - scope:
      path: ""
    values:
      type: "website"
      title: Aster Fialla
      directory: /images
      image: /portraits.png
      alt: "Aster, a person with pink hair, surrounded by illustrations of erself in many different art styles."
      image_path: /assets/images/posts/
  -
    scope:
      path: ""
      type: "twine"
    values:
      layout: "gamepage"
      verb: "Play"
  -
    scope:
      path: ""
      type: "piece"
    values:
      layout: "gamepage"
      verb: "Explore"
  -
    scope:
      path: ""
      type: "ttrpg"
    values:
      layout: "gamepage"
      verb: "Read"
  - scope:
      path: ""
      type: "posts"
    values:
      type: "article"
      layout: "posts"