title: Aster Fialla
description: Aster Fialla's portfolio, blog, and miscellaneous other things.
author: Aster Fialla
domain: asterfialla.com     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://asterfialla.com  # the base hostname and protocol for your site, e.g. http://example.com
layout: default
excerpt_separator: <!--more-->
collections_dir: collections
collections:
  twine:
    output: true
    permalink: games/:title
  piece:
    output: true
    permalink: games/:title
  ttrpg:
    output: true
    permalink: games/:title
plugins:
  - jekyll-feed

feed:
  icon: /images/avvie.png
  disable_in_development: true

defaults:
  - scope:
      path: ""
    values:
      type: "website"
      description: Aster Fialla's portfolio, blog, and miscellaneous other things.
      title: Aster Fialla
      directory: /images
      image: /portraits.png
  -
    scope:
      path: ""
      type: "twine"
    values:
      layout: "gamepage"
      verb: "Play"
  -
    scope:
      path: ""
      type: "piece"
    values:
      layout: "gamepage"
      verb: "Explore"
  -
    scope:
      path: ""
      type: "ttrpg"
    values:
      layout: "gamepage"
      verb: "Read"
  - scope:
      path: ""
      type: "posts"
    values:
      type: "article"
      layout: "posts"