title: Aster Fialla
description: The art and games of Aster Fialla
domain: asterfialla.com     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://asterfialla.com  # the base hostname and protocol for your site, e.g. http://example.com
layout: default
excerpt_separator: <!--more-->